
[data name:"complaintsByDate" source:"complaints-by-date" /]
[data name:"complaints" source:"complaints" /]
[data name:"responses" source:"company-responses" /]
[data name:"complaintsVL" source:"complaints-vl" /]
[data name:"quotes" source:"narratives" /]

[img className:"logo" src:"https://idyll-lang.github.io/idyll/images/logo.png" /]

[section className:"article-title"]

[hed]
United Complaints of America
[/hed]

[dek]
Analyzing over 700,000 complaints sent to the Consumer Financial Protection Bureau
[/dek]

[byline]
By: [link text:"Matthew Conlen" href:"https://twitter.com/mathisonian" /]
[/byline]

[/section]

[section ref:"body" className:"article-body"]

The Consumer Financial Protection Bureau (CFPB) is a lesser known 
government office meant to protect consumers. 
Created in the wake of the financial crisis, the bureau has been collecting 
consumers' complaints since 2011, 
and requiring that the companies provide a timely response to the complaint. All of these records
are stored in a database and are [link text:"available to the public" href:"https://www.consumerfinance.gov/data-research/consumer-complaints/" /].

The records are anonymized, but may still contain the original
"complaint narrative", as the CFBP calls it. The quotes below 
are randomly taken from the database. 


[QuoteDisplay quotes:quotes running:`true` /]


The number of complaints submitted each month has been steadily increasing since the 
bureau's creation. There were over 20,000 sumbitted in January 2017 alone.


[relative]

This trend may be optimistic. In February 
[link text:"Bloomberg reported" href:"https://www.bloomberg.com/news/articles/2017-02-08/the-cfpb-keeps-a-database-that-banks-can-t-wait-to-wipe" /]
that the CFPB is "a prime target for a Trump administration that has vowed to rewrite 
Obama-era financial rules and has suggested it will change the consumer bureau’s approach to policing financial markets."

Given that, it seemed an opportune time to dig into the database 
and see what I could learn.
  [div className:"pie"]
  [Chart type:"time" data:`complaintsByDate` /]
  [caption]Complaints sent to the CFPB each month[/caption]
  [/div]
[/relative]

## The Biggest Offenders

The most obvious question to ask is "What is the most complained about company in America?" That honor goes to 
the **Bank of America**, and it isn't even close. Bank of America has had 12,415 more complaints levied against 
it than the next runner up, Wells Fargo.

The table below shows the top ten most-complained-about companies. Most of them are large financial institutions, and this makes 
sense: many of the complaints deal with financial matters such as bank accounts, credit cards, morgages, loans, credit 
reports, and debt collection. These are the exactly types of things that the bureau was set up to deal with.

[ComplaintsTable data:complaints /]

One of the major services that the CFPB provides is requiring companies to respond to complaints within a certain 
timeframe (typically about two weeks). And it actually does work. About 97% of the registered complaints 
are marked as having received a response in a timely manner. This is important: if you spend some time looking 
at the consumer narratives, you'll notice that it isn't uncommon for people to be confused about a debt, or 
not understand why collectors are after them. Some people attempt to contact the company claiming a debt, 
but turn to the Consumer Financial Protection Bureau after receiving no response.

Whether or not consumers are happy 
with the responses that they get is harder to say with the given data. In the vast majority of cases, about 93%,
the company chooses to provide no public response, or the only public response is to admit no 
wrongdoing ("Company believes it acted appropriately as authorized by contract or law").

[relative]
[Table data:responses className:"responses" ref:"responses" /]
[Chart type:"pie" className:"pie" /]
[/relative]

## The Debt Collectors

One of the most surprising things for me 

## Explore

[/section]

